### ISSUE TITLE
Is a whitespace considered a valid part of a Katakana string?

### ISSUE THREAD

**Issue by kurtzhong** [gojp/kana#26]
Hi, sorry for this stupid question, I know nothing about a Japanese and find this repo be very helpful, just don't know whether in Japanese is a whitespace allowed in a Katakana string. Thanks.

**Comment by hermanschaaf** [comment]
Japanese text does not officially use whitespace, but there are certainly many cases in the wild where Japanese strings do contain whitespace. This is true for kanji as well as katakana and hiragana.

So it depends on what you are doing. In 90% of cases I would probably allow whitespace in katakana strings, and use the whitespace as a clue for where words start / end. Hope that helps! If you provide more information on what you are building, I may be able to help some more
