### ISSUE TITLE
ヂ is not handled correctly

### ISSUE THREAD

**Issue by akatsukle** [gojp/kana#28]
The (rare) katakana 'ヂ' is not handled correctly in `KanaToRomaji`.

Test program:
```
package main

import (
    "fmt"

    "github.com/gojp/kana"
)

func main() {
	var test = "アイウエオダヂヅデド"
	fmt.Printf("Kana results: %s -> %s", test, kana.KanaToRomaji(test))
}
```

Output:
`Kana results: アイウエオダヂヅデド -> aiueodaヂdudedo`

Expected output:
`Kana results: アイウエオダヂヅデド -> aiueodadidudedo`

If you are interested, I can make a PR to fix it.

**Comment by shawnps** [comment]
Thank you @akatsukle, I'd be more than happy to merge that PR if you make one.

**Comment by akatsukle** [comment]
Thanks for your prompt answer !

I took a deeper look, should we actually use the same transcription for both Katana and Hiragana unlike in my previous comment?
In which case, we would have:
`ダヂヅ` ->`dajidu`

While investigating, I also noticed that `ヂャ`, `ヂョ`, `ヂュ` were not handled either, adding them on the Hiragana model would give:
 `ヂャヂョヂュ` ->`jajoju`
Note that they are actually used in Japanese in for instance `ロヂャース`

Finally, I also noticed that `ヲ` was not handled either, and actually contains `オ` instead in the conversation table. I suppose this to be a mistake and we should have:
 `ヲ` ->`wo`
I've actually never seen that one outside of mangas, but since I was on it...

If you agree with me, then I'll proceed to add the test cases and to modify the table.

**Comment by shawnps** [comment]
> I took a deeper look, should we actually use the same transcription for both Katana and Hiragana unlike in my previous comment?
> In which case, we would have:
> `ダヂヅ` ->`dajidu`

Just to clarify, you mean ヂ => ji, rather than ヂ => di? That sounds good to me 👍 



> While investigating, I also noticed that `ヂャ`, `ヂョ`, `ヂュ` were not handled either, adding them on the Hiragana model would give:
> `ヂャヂョヂュ` ->`jajoju`
> Note that they are actually used in Japanese in for instance `ロヂャース`

Oh I see, it would be great if these were handled also.



> Finally, I also noticed that `ヲ` was not handled either, and actually contains `オ` instead in the conversation table. I suppose this to be a mistake and we should have:
> `ヲ` ->`wo`
> I've actually never seen that one outside of mangas, but since I was on it...

That definitely seems wrong to me, as you said it should be ヲ. If you are able to, please feel free to fix that one as well :)

Thanks a lot!

**Comment by akatsukle** [comment]
> Just to clarify, you mean ヂ => ji, rather than ヂ => di? That sounds good to me 👍

Yes exactly.

> Did you mean "Katakana model" rather than "Hiragana model" though?

Yes sorry for being unclear. I just meant "using the same transcription on katakana that we're already using on hiragana"

I'll open a PR later today then, thank you.
