### ISSUE TITLE
Support for half-width hiragana/katakana/romaji

### ISSUE THREAD

**Issue by richardgarnier** [gojp/kana#34]
Would you be ok to add support for half-width characters?

On top of my head, what I believe would be useful functions:
IsFullWidth(s string) bool
IsHalfWidth(s string) bool
ToFullWidth(s string) string (replace every half width character with their full-width counterpart)
ToHalfWidth(s string) string

Note: converting half-width/full-width, is not that easy, because 'ガ' becomes 'ｶﾞ'.
If you are interested into adding it to the library, I can get working on a PR.

**Comment by shawnps** [comment]
@akatsukle that certainly seems useful to me. I don't quite follow this part:

> Note: converting half-width/full-width, is not that easy, because 'ガ' becomes 'ｶﾞ'.

But in any case, if you want to work on this I'm more than happy to take a look at a PR 😄

**Comment by richardgarnier** [comment]
I mean, its a bit more complicated than a trivial lookup, because what is a single rune in full-width can become two runes in half-width. To my knowledge, there is no single rune 'ga' in half-width characters.

Looking more into it, the correct behavior for romajis is probably not covered by the above functions, so we probably need to have an api that is a bit more clever.

> But in any case, if you want to work on this I'm more than happy to take a look at a PR 😄

I'll work on that this weekend then :)

**Comment by shawnps** [comment]
Thanks @akatsukle I will keep an eye out for it!

**Comment by shawnps** [comment]
@akatsukle PS this library is used on a dictionary I maintain, https://nihongo.io. 

I am currently juggling a bunch of things ([Go Report Card](https://github.com/gojp/goreportcard), Master's degree, work, etc.) so I don't have much time at the moment. If this work interests you I have a bunch of ideas on how to make nihongo.io better. 

I would personally love to see verb conjugation support (like if you enter 食べました we deconstruct it into 食べる and look that up) and sentence splitting, which would most likely live in the https://github.com/gojp/japanese library.

This stuff is all free and open source so there's no monetary benefit to me or anyone else. Just mentioning it in case you're interested.

**Comment by richardgarnier** [comment]
> @akatsukle PS this library is used on a dictionary I maintain, https://nihongo.io.
> 
> I am currently juggling a bunch of things (Go Report Card, Master's degree, work, etc.) so I don't have much time at the moment. If this work interests you I have a bunch of ideas on how to make nihongo.io better.

Thank you for the offer. However I'm sorry, but I am not I'm not interested in getting committed to a project at the moment.

Regarding the present issue, I've finally get to work on it.
What would be your take on 1 vs １, or h vs ｈ?
For `IsFullWidth`, failing the test on 1 seems rather silly to me even though strictly speaking it should.
However `IsHalfWidth` failing on １ makes perfect sense.

For `ToFullWidth`, both behaviors (converting 1 to １, or leaving 1 as 1) are  making sense to me.
Similarly, `ToHalfWidth` does not have this issue.

For IsFullWidth/ToFullWidth, maybe the functions should take a boolean `ignoreNumeral` in order to be able to specify the desired behaviour.

Edit: I just realized there is the same issue with letters e.g. h vs ｈ.
Hence we should probably have a `ignoreAscii` flag, or maybe even clearer `processAscii`.
